"""add product stock

Revision ID: ac647263145e
Revises: ce2b63d2d741
Create Date: 2026-06-19 12:19:12.729151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac647263145e'
down_revision: Union[str, Sequence[str], None] = 'ce2b63d2d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
